name: Validate schema

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate-json-schema:
    name: v${{ matrix.schema }} schema
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema: [12, 13, 14-draft]
    steps:
      - uses: actions/checkout@v2
      - name: Install validator
        run: npm install @stoplight/spectral
      - name: Validate schema file against meta-schema
        run: npx spectral --fail-severity hint lint "${{ matrix.schema }}.json"
